### ISSUE TITLE
How to write unit tests with your daemon?

### ISSUE THREAD

**Issue by davetbo** [lifo101/php-daemon#14]
Hello,

I'm trying to unit test my code using your daemon. Whether I set daemonize to true or false, it blocks execution of everything else, so I can't seem to start it up and then do any more tests.

Do you have any advice or examples on how to test with this?  I've got other working examples of phpunit tests, so it's not like I don't know how to set up my unit tests, but I'm stumped on testing with your daemon.  I'm guessing it forks and blocks or something. 

Here's an example of what's going on.

<?php
require_once __DIR__ . '/../../classes/class-alo-cli-daemon-migrate-posts.php'; //this class extends your Daemon class

class ALO_CLI_Daemon_Migrate_Posts_Test extends WP_UnitTestCase {
    protected $mp;
    protected $logfile;
    
    public function setUp() {
        error_log("got into Migrate Posts setUp()");
        $this->logfile = __DIR__ . '/../logs/migrate_posts_service.log';
        $this->pidfile = __DIR__ . '/../locks/ALO_Client_Daemon_Migrate_Posts.pid';
        if (file_exists($this->logfile)) unlink($this->logfile);        
        $this->mp = ALO_CLI_Daemon_Migrate_Posts::getInstance()
            ->setDaemonize(false)
            ->setLoopInterval(20)
            ->setVerbose(true)
            ->setDebug(true)
            ->setDebugLevel(3)
            ->setLogFile($this->logfile)
            ->run();
        echo "Finished setUp()\n";
    }

And then I have some tests defined later in this test file.  If I run this, it hangs when I start the daemon.  Even the error log line (error_log("got into Migrate Posts setUp()");) 
that is called BEFORE starting the daemon doesn't actually print to the error log until after I kill the daemon process.  Also I tried echoing instead of error_log, but echo doesn't echo anything. I'm guessing that's also from starting up your daemon, because I can echo in my other unit tests.

Your daemon looks promising and I'd really love to get it working, but I need to be able to write testable code. Any advice?

Thanks,
Dave

**Comment by phuze** [comment]
Hi Dave,

Please post code inside of code tags; its not pleasant trying to read that mate.

The behaviour you are describing, admittedly, doesn't make much sense. Just to confirm, are you running this through cli mode?

Are you using tasks, or workers?

What does your daemon execute() function look like?

**Comment by phuze** [comment]
Upon inspecting the code you tried to post above, i see syntax errors and logic that I don't understand. Why delete the log file every time? You are also trying to execute your code inside a condition based on the existence of a log file which won't exist the second time around since you're deleting it. There's a lot of reasons why your code is failing here.

Did you take a look at the the [examples](https://github.com/lifo101/php-daemon/tree/master/examples/src)?

```php
logfile = __DIR__ . '/../logs/migrate_posts_service.log';
$this->pidfile = __DIR__ . '/../locks/ALO_Client_Daemon_Migrate_Posts.pid';

if (file_exists($this->logfile))
    unlink($this->logfile);
    $this->mp = ALO_CLI_Daemon_Migrate_Posts::getInstance()
    ->setDaemonize(false)
    ->setLoopInterval(20)
    ->setVerbose(true)
    ->setDebug(true)
    ->setDebugLevel(3)
    ->setLogFile($this->logfile)
    ->run();
    echo "Finished setUp()\n";
}
```

**Comment by lifo101** [comment]
If your code is separated into pieces of logic, then you should be able to unit test things w/o even using the Daemon itself. Your unit tests would simply create instances of your objects and call methods you want to test. All, w/o even creating a Daemon instance.

For instance, if you have a worker you want to test, simply create the Worker in your unit test, call whatever methods you need, check the result and move on.

Testing your main daemon loop logic will be harder and I have no suggestions for that. Generally, the logic in your main daemon loop should be as simple as polling a resource for some event to act on. All of your workers and task objects will be what handles the actual work load, which is where most of your testing will be.
