### ISSUE TITLE
Method returns current worker proc count?

### ISSUE THREAD

**Issue by wolverline** [lifo101/php-daemon#20]
I know Daemon sets workers within max proc but I need to check the proc count before a worker instance is created. This causes an issue for me since Promise doesn't return results from sudden death of a forked proc (some worker processes last for more than 6 hours) . I can't seem to find any method returning the current proc count.

**Comment by lifo101** [comment]
You can get the total active process count from the ProcessManager plugin. Something like this:

```php
$count = $this->plugin('process_manager')->count();
```

**Comment by wolverline** [comment]
Works well. Thank you.
