### ISSUE TITLE
Parameters on Task->run causing Fatal Error

### ISSUE THREAD

**Issue by AmpolSalesMike** [lifo101/php-daemon#21]
PHP Fatal error:  Declaration of Daemon\Tasks\Feeds::run($a, $b) must be compatible with Lifo\Daemon\Task\TaskInterface::run() in Test.php on line 5

Run defined as:
```php
    public function run($a, $b) // Two Parameters added.
    {
        $this->log("Task is running in the background! My PID=%d. I will now sleep for 2 seconds", getmypid());
        $this->log("$a, $b");
        sleep(2);
        $this->log("Task is done and will exit now");
    }
```
Called by:

```php
$this->task('Test', ['AAA', 'BBB']);
```

**Comment by phuze** [comment]
Don't pass the arguments in `run()`.
If you wish to pass arguments to a task, do so like this:

```
$this->task('MyTask', 'MyArgument1', 'MyArgument2');
```

```
public function run()
{
     $args = func_get_args();
     $MyArgument1 = $args[0];
     $MyArgument2 = $args[1];
}
```

**Comment by lifo101** [comment]
`TaskInterface` does not allow parameters on the run method. As mentioned above, you can use `func_get_args()` to fetch them within your run method. If you had used a straight callable, the parameters would have worked like normal. ie:

```php
$func = function($a, $b){ ... };
$this->task($func, $arg1, $arg2);
```
