### ISSUE TITLE
Daemon Restart Event Hook

### ISSUE THREAD

**Issue by phuze** [lifo101/php-daemon#22]
Referring to the wiki pages on both Events and Signal-Handling:
     https://github.com/lifo101/php-daemon/wiki/Events
     https://github.com/lifo101/php-daemon/wiki/Signal-Handling

Is there some way I can catch a restart event, and prevent it if a condition is met? The restart is being triggered by the daemon's auto restart mechanism `setAutoRestartInterval()`.

```php
<?php
return function () {
    CsvDaemon::getInstance()
        ->setDaemonize(true) # allow main daemon process to fork into the background
        ->setLoopInterval(10) # 10 second loop internal
        ->setAutoRestartInterval(3600) # restart the daemon every 1 hour
        ->setVerbose(true) # verbose logging
        ->setDebug(true) # debug logging enabled
        ->setDebugLevel(1) # 1 = low (not as detailed) ... 5 = high (maximum detail)
        ->setLogFile(DAEMON_LOG_CSV) # where to write the logs
        ->setCommand("sudo /usr/bin/php7.2 /var/daemons/launch.php 'CsvWatcher' '-d' > /dev/null")
        ->run(); # start the daemon
};
```

**Comment by lifo101** [comment]
sorry for delayed response. It's possible and not a terrible idea, but not something I can implement right this moment. It'd be a simple matter of adding an event hook into the restart code to check for a return value from an event like ON_RESTART_CHECK.

What's your use-case for stopping the auto-restart?

**Comment by purplekrayons** [comment]
I have a daemon responsible for processing a csv file into a message queue. These can at times end up being long running processes. I encountered situations where the auto restart was occurring regardless if there was a running process (task).

This is a sample log output demonstrating where this occurred:

The daemon `CsvWatcher` has a task, `CsvPrice`. While processing a CSV file which contained 13,313 rows, the daemon restart and the process was lost. In order to prevent this, I disabled the auto restart for this particular daemon.

```
Notice	CsvWatcher	2018-10-11 18:54:18.0946: 7391    12672: CsvPrice: [PRC][4000/13313] processed 4000 of 13313 records...
Notice	CsvWatcher	2018-10-11 18:54:37.2576: 7391    12672: CsvPrice: [PRC][5000/13313] processed 5000 of 13313 records...
Notice	CsvWatcher	2018-10-11 18:54:47.6626: 12836   12836: DEBUG: Daemon startup [Interval=10.0s] [Restart=1h]
Notice	CsvWatcher	2018-10-11 18:54:47.6637: 12836   12836: DEBUG: Daemon forked into child process. [PID=12837]
Notice	CsvWatcher	2018-10-11 18:54:47.0667: 12837   12837: DEBUG: Daemon::run loop started
```

These csv files are uploaded to the server at the same time each day, so I was looking for a means of conditionally preventing a restart during a specific time window (for example).

**Comment by phuze** [comment]
I have a daemon responsible for processing a csv file into a message queue. These can at times end up being long running processes. I encountered situations where the auto restart was occurring regardless if there was a running process (task).

This is a sample log output demonstrating where this occurred:

The daemon `CsvWatcher` has a task, `CsvPrice`. While processing a CSV file which contained 13,313 rows, the daemon restarted and the process was lost. In order to prevent this, I disabled the auto restart for this particular daemon.

```
Notice	CsvWatcher	2018-10-11 18:54:18.0946: 7391    12672: CsvPrice: [PRC][4000/13313] processed 4000 of 13313 records...
Notice	CsvWatcher	2018-10-11 18:54:37.2576: 7391    12672: CsvPrice: [PRC][5000/13313] processed 5000 of 13313 records...
Notice	CsvWatcher	2018-10-11 18:54:47.6626: 12836   12836: DEBUG: Daemon startup [Interval=10.0s] [Restart=1h]
Notice	CsvWatcher	2018-10-11 18:54:47.6637: 12836   12836: DEBUG: Daemon forked into child process. [PID=12837]
Notice	CsvWatcher	2018-10-11 18:54:47.0667: 12837   12837: DEBUG: Daemon::run loop started
```

These csv files are uploaded to the server at the same time each day, so I am looking for a means of conditionally preventing a restart during a specific time window (for example).

**Comment by lifo101** [comment]
I've implemented an event hook to prevent the auto-restart in my new code. I'm working on upgrading the Daemon for PHP 8.1. In the meantime, see the 'fix' below. You could implement an event listener and if you have running tasks, simply stop the propagation and it won't auto-restart.

This is not pushed into the current dev-master at this time.

```php
    // in Daemon.php
    private function autoRestart()
    {
        if (!$this->parent || !$this->daemonize) {
            return;
        }

        if ($this->autoRestartInterval && $this->getRuntime() >= $this->autoRestartInterval) {
            if (!$this->dispatch(DaemonEvent::ON_AUTO_RESTART)->isPropagationStopped()) {
                $this->restart();
            }
        }
    }
```
