### ISSUE TITLE
PHP 8.x

### ISSUE THREAD

**Issue by phuze** [lifo101/php-daemon#26]
As of PHP 8.x, a warning is thrown:

> The magic method Lifo\Daemon\Daemon::__wakeup() must have public visibility

This is related to a change made in 8.0.0 affecting magic methods. Per the [PHP doc](https://www.php.net/manual/en/language.oop5.magic.php):

> Warning
All magic methods, with the exception of [__construct()](https://www.php.net/manual/en/language.oop5.decon.php#object.construct), [__destruct()](https://www.php.net/manual/en/language.oop5.decon.php#object.destruct), and [__clone()](https://www.php.net/manual/en/language.oop5.cloning.php#object.clone), must be declared as public, otherwise an E_WARNING is emitted. Prior to PHP 8.0.0, no diagnostic was emitted for the magic methods [__sleep()](https://www.php.net/manual/en/language.oop5.magic.php#object.sleep), [__wakeup()](https://www.php.net/manual/en/language.oop5.magic.php#object.wakeup), [__serialize()](https://www.php.net/manual/en/language.oop5.magic.php#object.serialize), [__unserialize()](https://www.php.net/manual/en/language.oop5.magic.php#object.unserialize), and [__set_state()](https://www.php.net/manual/en/language.oop5.magic.php#object.set-state).

I grepped the code and found just the 1 occurrence within [Daemon.php](https://github.com/lifo101/php-daemon/blob/master/src/Lifo/Daemon/Daemon.php#L384).

```php
/** @noinspection PhpUnusedPrivateMethodInspection */
private function __wakeup()
{
    // un-serialization is disabled to the public
}
```

I haven't encountered any issues by making this a public function. However, it's not clear to me how this magic method is being used in the context of this library, and at the same, I only use tasks so I can't confirm the full scope of impact this change would have to workers and related functionality.

Can you advise, are there any concerns with making this a public function?

**Comment by lifo101** [comment]
I don't believe there would be any side-effects by making that public. I
think I was over zealous and made that private for no practical reason. I
think my original thought was there would never be a reason the Daemon (who
is a singleton) would ever need to be un/serialized so I made that private,
and none of the core Daemon code relies on serializating the Daemon itself.

-- Jason

**Comment by lifo101** [comment]
I'm starting to update the Daemon to work with PHP8.1, so this will be fixed soon. Will be starting a new branch, since a lot of backwards changes have occurred in the Symfony EventDispatcher too.
