### ISSUE TITLE
How do I pass variables to workers/tasks?

### ISSUE THREAD

**Issue by m3ll-0** [lifo101/php-daemon#8]
When I retrieve data on callback from a worker I want to pass that to a separate task i.e. to perform a database query but I don't know how to pass that to the task.

For example:
` $this->task("SendToDatabaseTask", $someArray);` 

Any idea? Thank you.

Edit: I am retarded, I found it.

**Comment by phuze** [comment]
How did you consume the passed arguments in your tasks?
