### ISSUE TITLE
Sysv Error:  Error fetching message from queue

### ISSUE THREAD

**Issue by m3ll-0** [lifo101/php-daemon#9]
I have this in my execute() method daemon:

        if ($this->getLoopIterations() % 5 == 0) 
        {
            $this->StartMbcGetWorker();
        }
        if ($this->getLoopIterations() % 8 == 0) 
        {
            $this->StartTrhGetWorker();
        }

But after executing I get this output:

> 2018-02-12 14:02:47.7789: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.7999: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.8209: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.8418: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.8627: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.8836: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.9045: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.9255: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.9464: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.9673: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument
> 2018-02-12 14:02:47.9882: 17335   17337: SysV Error: Error fetching message from queue: ERR=22 Invalid argument

... etc ....

This error happens when trying to start a task/worker in the callback of a worker. E.g. when the second worker is supposed to start at 8 seconds this happens when that Task/Worker is supposed to start. 

This is from the StartMbcGetWorker method:

```
$MbcGetWorker = $this->worker('MainMbcGetWorker');
$MbcGetWorker->MainMbcGetWorker()->then(function ($valueArray){
$this->task(new SendToDatabaseTask(), $valueArray, $this->currentMbcCall); // <- Gives SysV error
           $this->Anotherfunction(); // <- Gives Sysv Error
        });
```

Very confusing, I thought that this was supposed to work? Any idea maybe? Thank you.

**Comment by lifo101** [comment]
You can't start a Task from within a Worker process. That essentially forks a sub-process within a sub-process, breaking the ProcessManager's ability to track processes properly. The fact is, since your worker is already running in a background process, there's no need to start a task. Just continue doing whatever work you need and then finally return when ready.
